name: deploy-review

on: 
  push:
    branches:
      - main

jobs:
  test-frontend:
    name: Test Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.1.0'  # Adjust this to your Node.js version

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install
        working-directory: ./sin-trade-fe

      - name: Run tests
        run: pnpm test
        working-directory: ./sin-trade-fe

  test-backend:
    name: Test Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.4'  # Adjust this to your Python version

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r sin-trade-be/requirements.txt

      - name: Run tests
        run: |
          source venv/bin/activate
          pip install pytest
          pytest
        working-directory: ./sin-trade-be

  test-ds:
    name: Test Data Science Service
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.4'  # Adjust this to your Python version

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r sin-trade-ds/requirements.txt

      - name: Run tests
        run: |
          source venv/bin/activate
          pip install pytest
          pytest
        working-directory: ./sin-trade-ds

  deploy-frontend:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    needs: test-frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.1.0'  # Adjust this to your Node.js version

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install
        working-directory: ./sin-trade-fe

      - name: Build frontend
        run: pnpm run build
        working-directory: ./sin-trade-fe

      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          git remote add heroku https://git.heroku.com/sin-trade-fe.git
          git push heroku `git subtree split --prefix sin-trade-fe main`:refs/heads/main --force

  deploy-backend:
    name: Deploy Backend
    runs-on: ubuntu-latest
    needs: test-backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.4'  # Adjust this to your Python version

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r sin-trade-be/requirements.txt

      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          git remote add heroku hhttps://git.heroku.com/sin-trade-be.git
          git push heroku `git subtree split --prefix sin-trade-be main`:refs/heads/main --force

  deploy-ds:
    name: Deploy Data Science Service
    runs-on: ubuntu-latest
    needs: test-ds

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.4'  # Adjust this to your Python version

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r sin-trade-ds/requirements.txt

      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          git remote add heroku https://git.heroku.com/sin-trade-ds.git
          git push heroku `git subtree split --prefix sin-trade-ds main`:refs/heads/main --force