name: deploy-review

on: 
  push:
    branches:
      - main

jobs:
  
  test-frontend:
    name: Test Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.1.0'  # Adjust this to your Node.js version

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install
        working-directory: ./sin-trade-fe

      - name: Run tests
        run: pnpm test
        working-directory: ./sin-trade-fe

  test-backend:
    name: Test Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.4'  # Adjust this to your Python version

      - name: Install dependencies
        working-directory: ./sin-trade-be
        run: |
          python -m venv sin-trade-be/venv
          source sin-trade-be/venv/bin/activate
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        working-directory: ./sin-trade-be
        run: |
          source sin-trade-be/venv/bin/activate
          pytest

  test-ds:
    name: Test Data Science Service
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.4'  # Adjust this to your Python version

      - name: Install dependencies
        working-directory: ./sin-trade-ds
        run: |
          python -m venv sin-trade-ds/venv
          source sin-trade-ds/venv/bin/activate
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        working-directory: ./sin-trade-ds
        run: |
          source sin-trade-ds/venv/bin/activate
          pytest



  deploy-frontend:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    needs: test-frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.1.0'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install
        working-directory: ./sin-trade-fe

      - name: Build frontend
        run: pnpm run build
        working-directory: ./sin-trade-fe

      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh

      - name: Authenticate with Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
        run: |
          echo "machine git.heroku.com login $HEROKU_EMAIL password $HEROKU_API_KEY" > ~/.netrc
          chmod 600 ~/.netrc

      - name: Add Heroku remote
        run: |
          if ! git remote | grep heroku; then
            heroku git:remote -a sin-trade-fe
          fi

      - name: Deploy to Heroku
        run: git push heroku main --force

  deploy-backend:
    name: Deploy Backend
    runs-on: ubuntu-latest
    needs: test-backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.4'  # Adjust this to your Python version

      - name: Install dependencies
        working-directory: ./sin-trade-be
        run: |
          python -m venv sin-trade-be/venv
          source sin-trade-be/venv/bin/activate
          pip install -r requirements.txt

      - name: Create Procfile
        working-directory: ./sin-trade-be
        run: "echo 'web: gunicorn src.app:app' > Procfile"
      
      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh
      
      - name: Authenticate with Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
        run: |
          echo "machine git.heroku.com login $HEROKU_EMAIL password $HEROKU_API_KEY" > ~/.netrc
          chmod 600 ~/.netrc

      - name: Add Heroku remote
        run: |
          if ! git remote | grep heroku; then
            heroku git:remote -a sin-trade-be
          fi

      - name: Deploy to Heroku
        run: git push heroku main --force

  deploy-ds:
    name: Deploy Data Science Service
    runs-on: ubuntu-latest
    needs: test-ds

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.4'  # Adjust this to your Python version

      - name: Install dependencies
        working-directory: ./sin-trade-ds
        run: |
          python -m venv sin-trade-ds/venv
          source sin-trade-ds/venv/bin/activate
          pip install -r requirements.txt

      - name: Create Procfile
        working-directory: ./sin-trade-ds
        run: "echo 'web: gunicorn src.app:app' > Procfile"

      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh
      
      - name: Authenticate with Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
        run: |
          echo "machine git.heroku.com login $HEROKU_EMAIL password $HEROKU_API_KEY" > ~/.netrc
          chmod 600 ~/.netrc

      - name: Add Heroku remote
        run: |
          if ! git remote | grep heroku; then
            heroku git:remote -a sin-trade-ds
          fi

      - name: Deploy to Heroku
        run: git push heroku main --force